INSERT INTO JBPM4_ID_GROUP VALUES (1,0,'manager','manager','security-role',NULL);
INSERT INTO JBPM4_ID_GROUP VALUES (2,0,'administrator','administrator','security-role',NULL);
INSERT INTO JBPM4_ID_GROUP VALUES (3,0,'user','user','security-role',NULL);
INSERT INTO JBPM4_ID_GROUP VALUES(4,0,'sales','sales',NULL,NULL);

INSERT INTO JBPM4_ID_USER VALUES (1,0,'alex','password','Alex',NULL,'alex@jbpm.org');
INSERT INTO JBPM4_ID_USER VALUES (2,0,'mike','password','Mike',NULL,'mike@jbpm.org');
INSERT INTO JBPM4_ID_USER VALUES (3,0,'peter','password','Peter',NULL,'peter@jbpm.org');
INSERT INTO JBPM4_ID_USER VALUES (4,0,'mary','password','Mary',NULL,'mary@jbpm.org');

INSERT INTO JBPM4_ID_MEMBERSHIP VALUES (1,0,1,2,NULL);
INSERT INTO JBPM4_ID_MEMBERSHIP VALUES (2,0,2,1,NULL);
INSERT INTO JBPM4_ID_MEMBERSHIP VALUES (3,0,3,3,NULL);
INSERT INTO JBPM4_ID_MEMBERSHIP VALUES (4,0,3,4,NULL);
INSERT INTO JBPM4_ID_MEMBERSHIP VALUES (5,0,4,3,NULL);
INSERT INTO JBPM4_ID_MEMBERSHIP VALUES (6,0,4,4,NULL);
